import {FEATURES} from './feature-registry.js';
import {ROOTS,SCALES,CHORDS,MODES,CIRCLE,PROGRESSIONS,pretty,noteName,pitchClass,patternNames,intervalLabel,inversionName,palette,progressionChords,identify} from './theory.js';
export const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options = (values,selected) => values.map(item=>{const [value,label]=Array.isArray(item)?item:[item,pretty(item)];return `<option value="${escape(value)}" ${value===selected?'selected':''}>${escape(label)}</option>`;}).join('');
export const select = (label,field,values,value) => `<label class="field"><span>${label}</span><select aria-label="${escape(label)}" data-field="${field}">${options(values,value)}</select></label>`;
const check = (label,field,value) => `<label class="check"><input type="checkbox" data-field="${field}" ${value?'checked':''}>${label}</label>`;
const action = (label,id,primary=false,extra='') => `<button type="button" data-action="${id}" class="${primary?'primary':''}" ${extra}>${label}</button>`;
const rootSelect = s=>select('Root note','root',ROOTS,s.root);
const qualitySelect = s=>select('Chord quality','quality',Object.entries(CHORDS).map(([k,v])=>[k,v.label]),s.quality);
const register = s=>select('Register','anchor',[[36,'Low · C2'],[48,'Lower middle · C3'],[60,'Middle · C4'],[72,'High · C5']],s.anchor);
const inversions = s=>select('Inversion','inversion',CHORDS[s.quality].intervals.map((_,i)=>[i,inversionName(i)]),s.inversion);
const directions = s=>`<div class="field-row">${select('Direction','direction',[['up','Ascending'],['down','Descending']],s.direction)}${select('Octaves','octaves',[[1,'One'],[2,'Two']],s.octaves)}</div>`;
export function controls(s,quiz){
  switch(s.mode){
    case 'notes': return `<div class="note-chips">${(s.accidental==='flats'?['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B']:['C','C#','D','D#','E','F','F#','G','G#','A','A#','B']).map((n,i)=>`<button data-action="filter" data-value="${i}" aria-pressed="${s.filter.includes(i)}" class="${s.filter.includes(i)?'active':''}">${pretty(n)}</button>`).join('')}</div><div class="button-row" style="margin-top:18px">${action('Show all notes','clear-filter')}</div><details class="help"><summary>Guide</summary><p>C is just to the left of each group of two black keys. The dot marks middle C.</p></details>`;
    case 'scales': return `${rootSelect(s)}${select('Scale','scale',Object.entries(SCALES).map(([k,v])=>[k,v.label]),s.scale)}${register(s)}${directions(s)}${action('▶ Play scale','play',true)}${s.scale==='melodic'?'<details class="help"><summary>Guide</summary><p>Classical melodic minor raises the 6th and 7th ascending, then uses natural minor descending.</p></details>':'<details class="help"><summary>Guide</summary><p>The bright green key is your root. Come back to it to hear the scale resolve.</p></details>'}`;
    case 'chords':return `${rootSelect(s)}${qualitySelect(s)}${inversions(s)}${register(s)}${select('Highlight','chordView',[['voicing','This voicing'],['tones','Chord tones everywhere']],s.chordView)}${check('Left-hand root + right-hand chord','split',s.split)}${action('▶ Play chord','play',true)}`;
    case 'arpeggios':return `${rootSelect(s)}${qualitySelect(s)}${inversions(s)}${register(s)}${directions(s)}${action('▶ Play arpeggio','play',true)}`;
    case 'positions':return `${select('Starting note','root',['C','G','D','A','E','F'],s.root)}${select('Pattern','positionQuality',[['major','Major'],['minor','Minor']],s.positionQuality)}${select('Hand','hand',[['right','Right hand'],['left','Left hand']],s.hand)}${register(s)}${action('▶ Hear pattern','play',true)}<details class="help"><summary>Guide</summary><p>1 is your thumb; 5 is your little finger. Let your hand stay relaxed. These are starting patterns, not full-scale fingerings.</p></details>`;
    case 'identifier':return `<p>Tap notes or hold a MIDI chord.</p><div class="button-row">${action('▶ Hear selection','play',true)}${action('Clear','clear-selection')}</div><details class="help"><summary>Guide</summary><p>The lowest note is the bass. Move it to another chord tone to discover an inversion.</p></details>`;
    case 'palette':return `${rootSelect(s)}${select('Key or mode','paletteMode',MODES.map(k=>[k,SCALES[k].label]),s.paletteMode)}${select('Chord family','family',[['triad','Triads'],['sus2','Suspended 2nds'],['sus4','Suspended 4ths'],['seventh','Sevenths']],s.family)}${register(s)}<details class="help"><summary>Guide</summary><p>Choose a chord card to hear it and see its notes. Altered cards keep every tone inside the selected scale.</p></details>`;
    case 'circle':{const names=patternNames(s.root,SCALES.major),sharps=names.join('').split('#').length-1,flats=names.join('').split('b').length-1;return `${rootSelect(s)}<h2>${pretty(s.root)} major</h2><p>${sharps?`${sharps} sharp${sharps===1?'':'s'}`:flats?`${flats} flat${flats===1?'':'s'}`:'No sharps or flats'}</p><p>Relative minor: <strong>${pretty(names[5])} minor</strong></p><div class="button-row">${action('Explore scale','circle-scale',true)}${action('Explore chords','circle-chords')}</div><details class="help"><summary>Guide</summary><p>Clockwise adds a sharp; anticlockwise adds a flat. Adjacent keys share six of their seven notes.</p></details>`;}
    case 'progressions':return `${rootSelect(s)}${select('Progression','progression',PROGRESSIONS.map(p=>[p.id,`${p.name} · ${p.mood}`]),s.progression)}${register(s)}${check('Add a left-hand root','split',s.split)}<div class="button-row">${action('▶ Play progression','play',true)}${action('Save','save')}</div><div class="saved-list"><p class="eyebrow" style="margin-top:24px">SAVED PROGRESSIONS</p>${s.saved.length?s.saved.map((p,i)=>`<div class="saved-row">${action(`${pretty(p.root)} · ${PROGRESSIONS.find(v=>v.id===p.id).name}`,'load-saved',false,`data-index="${i}"`)}${action('×','delete-saved',false,`data-index="${i}" aria-label="Remove saved progression"`)}</div>`).join(''):'<p class="small">Save a favourite to return to it later.</p>'}</div>`;
    case 'quiz':return `${select('Practice type','quizType',[['find','Find a note'],['name','Name a note'],['chord','Build a chord'],['inversion','Play an inversion']],s.quizType)}${action(quiz&&!quiz.complete?'Restart ten questions':'Start ten questions','start-quiz',true)}<details class="help"><summary>Guide</summary><p>There’s no timer. Try it, check it, learn from it. Revealed answers don’t count towards your score.</p></details><p class="small">All-time: ${s.stats.correct} / ${s.stats.total} correct<br>${s.stats.sessions} completed sessions</p>`;
    default:return '';
  }
}
const tokens=(names,intervals,degrees)=>`<div class="token-row">${names.map((name,i)=>`<span class="note-token ${i===0?'root-token':''}">${pretty(escape(name))}<small>${intervalLabel(intervals[i],degrees?.[i])}</small></span>`).join('')}</div>`;
export function details(s,context){
  const {selected=[],quiz,focusChord}=context;
  if(s.mode==='notes')return `${tokens(['C','D','E','F','G','A','B'],[0,2,4,5,7,9,11])}<details class="help"><summary>Guide</summary><p>The musical alphabet runs from A to G, then starts again. Each repeat is an octave higher. Black keys sit between neighbouring white keys, except E–F and B–C.</p></details>`;
  if(['scales','positions','chords','arpeggios'].includes(s.mode)){
    const pattern=s.mode==='scales'?SCALES[s.scale==='melodic'&&s.direction==='down'?'minor':s.scale]:s.mode==='positions'?{intervals:s.positionQuality==='major'?[0,2,4,5,7]:[0,2,3,5,7]}:CHORDS[s.quality];
    const title=`${pretty(s.root)} ${s.mode==='scales'?SCALES[s.scale].label.toLowerCase():s.mode==='positions'?s.positionQuality+' five-finger pattern':CHORDS[s.quality].label.toLowerCase()}`;
    return `<p class="eyebrow">${s.mode==='chords'||s.mode==='arpeggios'?inversionName(s.inversion).toUpperCase():'THE NOTES INSIDE'}</p><h2>${title}</h2>${tokens(patternNames(s.root,pattern),pattern.intervals,pattern.degrees || (pattern.intervals.length===7 ? [0,1,2,3,4,5,6] : undefined))}<details class="help"><summary>Guide</summary><p>${s.mode==='chords'||s.mode==='arpeggios'?`${inversionName(s.inversion)} puts ${pretty(patternNames(s.root,CHORDS[s.quality])[s.inversion])} at the bottom of the right-hand voicing.${s.split&&s.mode==='chords'?' The added left-hand root becomes the overall bass.':''} The chord keeps the same pitch classes.`:s.mode==='positions'?`From low to high: ${s.hand==='right'?'1 · 2 · 3 · 4 · 5':'5 · 4 · 3 · 2 · 1'}. Keep the fingers gently curved.`:'Play slowly and listen to the distance between each pair of notes.'}</p></details>`;
  }
  if(s.mode==='identifier'){
    const matches=identify(selected,s.accidental);
    return `<div id="identifier-result">${selected.length?`<h2>${selected.map(n=>pretty(noteName(n,s.accidental,true))).join(' · ')}</h2>${matches.length?matches.map(m=>`<p><strong class="chord-name">${escape(m.label)}</strong> <span class="muted">${inversionName(m.inversion)} · bass ${pretty(m.bass)}</span></p>`).join(''):'<p>No exact match in the chord library yet. Try three or four different chord tones.</p>'}`:'<p>Select notes to identify a chord.</p>'}</div>`;
  }
  if(s.mode==='palette')return `<p class="eyebrow">${pretty(s.root)} ${SCALES[s.paletteMode].label.toUpperCase()}</p><div class="palette-grid">${palette(s.root,s.paletteMode,s.family).map((c,i)=>`<button class="chord-tile ${focusChord?.index===i?'active':''}" data-action="palette-chord" data-index="${i}"><small>DEGREE ${i+1}</small><strong>${escape(c.label)}</strong><small>${c.quality?CHORDS[c.quality].label:'Scale-specific voicing'}</small></button>`).join('')}</div><details class="help"><summary>Guide</summary><p>${focusChord?`Selected: ${focusChord.notes.map(n=>pretty(noteName(n,s.accidental))).join(' · ')}`:'These chords are built from the notes of your chosen scale.'}</p></details>`;
  if(s.mode==='circle')return `<div class="circle-wrap"><div class="circle-center">${pretty(s.root)}<small>MAJOR</small></div>${CIRCLE.map(([root,minor],i)=>{const angle=i*Math.PI/6-Math.PI/2;return `<button class="circle-key ${pitchClass(root)===pitchClass(s.root)?'active':''}" style="left:${50+41*Math.cos(angle)}%;top:${50+41*Math.sin(angle)}%" data-action="circle-root" data-value="${root}" aria-label="${root} major, relative minor ${minor}">${pretty(root)}</button>`;}).join('')}</div><p class="eyebrow">DIATONIC CHORDS</p><div class="palette-grid">${palette(s.root).map((c,i)=>`<button class="chord-tile" data-action="diatonic" data-index="${i}"><small>${['I','ii','iii','IV','V','vi','vii°'][i]}</small><strong>${escape(c.label)}</strong></button>`).join('')}</div>`;
  if(s.mode==='progressions'){
    const p=PROGRESSIONS.find(p=>p.id===s.progression);
    return `<p class="eyebrow">${p.mood.toUpperCase()} / ${pretty(s.root)} MAJOR</p><h2>${p.name}</h2><div class="palette-grid">${progressionChords(s.root,s.progression).map((c,i)=>`<button class="chord-tile" data-action="progression-chord" data-index="${i}"><small>${c.roman}</small><strong>${escape(c.label)}</strong><small>${c.function}</small></button>`).join('')}</div><details class="help"><summary>Guide</summary><p>${p.description} Try improvising with ${pretty(s.root)} major while these chords play.</p></details>`;
  }
  if(s.mode==='quiz'){
    if(!quiz)return `<p>Choose a quiz. Answer onscreen or with MIDI.</p>`;
    if(quiz.complete)return `<p class="eyebrow">SESSION COMPLETE</p><h2>${quiz.score} / ${quiz.questions.length} correct</h2><p>${quiz.score===quiz.questions.length?'A clean sweep. Try another practice type.':'Every attempt is a step forward. Revisit the questions below.'}</p><ul class="quiz-summary">${quiz.results.map(r=>`<li>${r.correct?'✓':r.revealed?'↳':'○'} ${escape(r.question.prompt)}<br><span class="muted">${escape(r.question.answer)}</span></li>`).join('')}</ul><div class="button-row">${action('Try another ten','start-quiz',true)}${quiz.results.some(r=>!r.correct)?action('Retry missed questions','retry-quiz'):''}</div>`;
    const q=quiz.current;
    return `<p class="eyebrow">QUESTION ${quiz.index+1} OF ${quiz.questions.length} · ${quiz.score} CORRECT</p><div class="progress-track"><i style="width:${quiz.index/quiz.questions.length*100}%"></i></div><p class="quiz-prompt">${escape(q.prompt)}</p>${q.type==='name'?`<div class="note-chips">${['C','D','E','F','G','A','B'].map(n=>action(n,'answer-name',false,`data-value="${pitchClass(n)}" ${quiz.answered?'disabled':''}`)).join('')}</div>`:`<p class="small">${q.type==='find'?'Play one note in any octave.':'Tap keys to select your answer, or hold a MIDI chord.'}</p><div class="live-notes" id="quiz-selection">${selected.map(n=>pretty(noteName(n,s.accidental,true))).join(' · ')||'No notes selected'}</div>`}<div class="result-message" role="status">${escape(quiz.feedback)}</div><div class="button-row">${quiz.answered?action(quiz.index===quiz.questions.length-1?'See results':'Next question','next-question',true):`${q.type!=='name'?action('Check answer','check-answer',true):''}${action('Reveal answer','reveal')}${q.type!=='name'?action('Clear selection','clear-selection'):''}`}</div>`;
  }
  return '';
}
for(const feature of FEATURES){customElements.define(feature.tag,class extends HTMLElement{configure(state,context){this.innerHTML=controls(state,context.quiz);}});}
